- ros_topic_name: "/lidar/cloud"
  gz_topic_name: "/lidar/cloud/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: GZ_TO_ROS

- topic_name: "/lidar/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS

- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS

# Ground-truth odometry for VIO bridge -> PX4 visual odometry
- ros_topic_name: "/model/x500_gzlidar_0/odometry_with_covariance"
  gz_topic_name: "/model/x500_gzlidar_0/odometry_with_covariance"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.OdometryWithCovariance"
  direction: GZ_TO_ROS
